### ISSUE TITLE
Magic Passport Unauthorized In React Native

### ISSUE THREAD

**Issue by jackien1** [magiclabs/passport-magic#7]
I followed all the steps in the full Node.js tutorial for the Magic Admin server and linked it with the React Native Magic client. While the login route of the Magic Admin server works, the index ("/") route continues to show error 401 (unauthorized). I'm not sure how to resolve this issue.

Here is my React Native code:
```
const didToken = await m.auth.loginWithMagicLink({
email: "jackieni2002@gmail.com",
});

axios.defaults.headers.common[
"Authorization"
] = `Bearer ${didToken}`;

// this works
await axios.post("https://8405a38c.ngrok.io/api/auth/login");

// this throws an authentication error
await axios.get("https://8405a38c.ngrok.io/api/auth");

```

This is my Node.js server code:
```
router.get("/", async (req, res) => {
  if (req.isAuthenticated()) {
    return res.status(200).json(req.user).end();
  } else {
    return res.status(401).end(`User is not logged in.`);
  }
});

router.post("/login", passport.authenticate("magic"), (req, res) => {
  if (req.user) {
    res.status(200).end("User is logged in.");
  } else {
    return res.status(401).end("Could not log user in.");
  }
});
```

**Comment by Ethella** [comment]
@smithki Could you take a look for @jackien1 on Tuesday?

**Comment by smithki** [comment]
@jackien1 -- Do you mind posting a more complete code sample? There is context missing in your snippet, such as how the express app is set up and which middlewares are provided in which order. In particular, I'm curious to see how you've configured `express-session`.

**Comment by smithki** [comment]
Also, here is a Passport JS issue which is helpful for troubleshooting why `req.isAuthenticated()` might consistently return `false`: https://github.com/jaredhanson/passport/issues/525

**Comment by jackien1** [comment]
> Also, here is a Passport JS issue which is helpful for troubleshooting why `req.isAuthenticated()` might consistently return `false`: [jaredhanson/passport#525](https://github.com/jaredhanson/passport/issues/525)

I think the issue resolves around cookies and React Native. Since React Native does not save cookies, I think that is why req.isAuthenticated() does not work. Do you still need my full code?

**Comment by jackien1** [comment]
@smithki

**Comment by smithki** [comment]
Thanks for the additional context. I am not a React Native expert by any means, but I think cookies are managed by the native network stack, which should manage cookies automatically (depending on the platform): https://github.com/facebook/react-native/issues/1274

@Ethella, feel free to chime in with more information from the React Native side. This is not really my wheelhouse.

**Comment by Ethella** [comment]
The issue should be related to the platform. Closing due to inactive.

**Comment by geordidearns** [comment]
Hey! I'm seeing this also, it logs in fine, then when I try to request another endpoint it's not authorized - here is my config for the session. If you need more information just let me know! Happy to add it

`app.use(
  session({
    secret: "trying out magic",
    resave: false,
    saveUninitialized: true,
    cookie: {
      maxAge: 60 * 60 * 1000, // 1 hour
      secure: false, // Uncomment this line to enforce HTTPS protocol.
      sameSite: true,
    },
  })
);
app.use(passport.initialize());
app.use(passport.session());`
